project:
  type: book
  
book:
  title: "Charting with Candor"
  author: 'David Churchman'
  date: '8/30/2024'
  page-navigation: true
  chapters: 
    - index.qmd
    - references.qmd
    
  

format:
  html:
    theme:
      - lux
      - candor.scss
    code-link: true
    
    author-meta: 'David Churchman'
    callout-appearance: simple
        

editor: visual
